global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "bot"
    metrics_path: /metrics
    static_configs:
      - targets: ["bot:9000"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis_exporter:9121"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
